In [1]:
import numpy as np
import pandas as pd

In [2]:
lst = ['USA','Germany','Italy','Japan']
ind = ['a','b','c','d']
df = pd.DataFrame(lst)
print(df)

         0
0      USA
1  Germany
2    Italy
3    Japan

In [7]:
from numpy.random import randn
np.random.seed(101)

In [16]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [17]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [21]:
df['new']=df['W']+df['X']

In [22]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [26]:
df.drop('W',axis=1)

          X         Y         Z       new
A  1.693723 -1.706086 -1.159119  1.996388
B  0.390528  0.166905  0.184502  0.255687
C  0.072960  0.638787  0.329646  0.880666
D -0.754070 -0.943406  0.484752 -1.251174
E  1.901755  0.238127  1.996652  1.784981

In [30]:
df.shape

(5, 5)

In [31]:
df.columns

Index(['W', 'X', 'Y', 'Z', 'new'], dtype='object')

In [8]:
df.fillna("W")

NameError: name 'df' is not defined